### ISSUE TITLE
"Where to be posted?" cannot load

### ISSUE THREAD

**Issue by jakejcheng** [slackapi/template-announcement-approvals#5]
I couldn't get "Where to be posted?" to load. "Select an approver" loads just fine but "Where to be posted?" will get stuck at the loading state. I tried to add another "channels:read" scope but it still doesn't work. Any thoughts?

EDIT: I have "chat:write", "conversations:read", "conversations.app_home:create" set already.

**Comment by deefofum** [comment]
I have this issue as well. Can't seem to figure it out.

**Comment by radamsiii** [comment]
Any idea what part I would edit so that it doesn't pull all users for approval and instead just one person or all admins for approval?

**Comment by girliemac** [comment]
👋  Sorry for the late reply!

If no channels are loaded, the bot may not have been added in any channels. Invite bots to the channels by `/invite @approval-bot` (or whatever the name of your bot) first. Then you should see all the channels the bot has the right to post.

Now I realize this may not be the perfect scenario (and not so intuitive), but hopefully, you can improve your version for a better bot with better UX.

**Comment by girliemac** [comment]
Also, make sure you have set the **Options load URL** under **Interactive Components > Message Menus**. This is where a custom dropdown list is loaded.

**Comment by mronceray** [comment]
I have the same issue and i followed what @girliemac give us. When I click on the dropdown menu I have this error in my console:
`(node:17476) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'next_cursor' of undefined
    at Object.findAuthedChannels (/root/template-announcement-approvals/src/channels.js:28:25)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async /root/template-announcement-approvals/src/index.js:174:23
(node:17476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)`

**Comment by leslie-alldridge** [comment]
@jakejcheng I tried this repo today and it works fine. If you're not still experiencing the problem feel free to close this issue 😃
